### ISSUE TITLE
Look at Zephyr for what could be leveraged for automatic checking of pull requests for Doxygen-compatible comments

### ISSUE THREAD

**Issue by nathalie-ckc** [OpenAMP/openamp-system-reference#16]
From https://github.com/OpenAMP/openamp-system-reference/wiki/OpenAMP-System-Reference-Meeting-Notes-2023#user-content-20230322 

(Filing GH Issues for relevant action items from System Reference calls)

**Comment by wmamills** [comment]
@arnopo Now that we have doc PR review links, is this issue closed?

**Comment by arnopo** [comment]
Yes  I close it
