### ISSUE TITLE
Investigate best way to integrate multiple repos

### ISSUE THREAD

**Issue by nathalie-ckc** [OpenAMP/openamp-system-reference#18]
- [ ] Arnaud can try to modify his CI to try submodule, to see how easy to work with it

- [ ] Bill will experiment Zephyr integration idea with West

(Filing GH Issues for relevant action items from System Reference calls. From https://github.com/OpenAMP/openamp-system-reference/wiki/OpenAMP-System-Reference-Working-Group-Meeting-Notes#user-content-Action_items-4)

**Comment by wmamills** [comment]
@arnopo our west manifest aprouch solves this right?
Ok to close this issue now?

**Comment by arnopo** [comment]
Yes I close It
