### ISSUE TITLE
examples: dts: Update example dts for zcu102 and kv260 to work with zephyr rpmsg_multi_services demo

### ISSUE THREAD

**Issue by tnmysh** [OpenAMP/openamp-system-reference#27]
zephyr dts for xilinx mailbox is here: https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/xilinx/zynqmp_rpu.dtsi#L35

Current example dts for zcu102 does not contain counter part of this node.
Currently lockstep mode is supported only for zephyr. So, lockstep mode dts need to be updated to make zephyr demo work on zcu102.

Also, kv260 device-tree needs to be pushed from latest petalinux.

**Comment by tnmysh** [comment]
@wmamills, @uLipe FYI.

**Comment by tnmysh** [comment]
@wmamills are we still planning to run baremetal firmware as part of CI ? Or only zephyr firmware for zynqmp platforms?

I would like to change IPI node that is used to communicate with Remote core in dts. After that current baremetal firmware binaries won't work, we will have to update it. Is that ok?

**Comment by wmamills** [comment]
I would like to run baremetal also but they can be new binaries.  We don't need to run the old ones.
Does that help?

If that is not possible we can start with just Zephyr.

**Comment by tnmysh** [comment]
Ok, first we target zephyr. Once it's done we can update baremetal binaries..

**Comment by tnmysh** [comment]
@wmamills, here is the PR for kv260 starter kit dts: https://github.com/OpenAMP/openamp-system-reference/pull/30

**Comment by tnmysh** [comment]
@wmamills I can't bring-up ethernet port on kv260 board. I wanted to check with you if ethernet is working on your side?
This makes it difficult to look at kernel logs once r5 zephyr firmware starts as uart 1 is taken by r5.

**Comment by uLipe** [comment]
Just to provide information, the ethernet port should shows up, I can access my kv260
board through ssh.

**Comment by tnmysh** [comment]
@uLipe what dts are you using? Also, anything special you need to mention on u-boot command line?

**Comment by tnmysh** [comment]
so, I can see eth0 interface, but don't see IP address assigned to it:

**Comment by tnmysh** [comment]
I got it, I think there was connection problem.

**Comment by wmamills** [comment]
This issue was addressed in v2023.10 and never closed so I am closing now.
