### ISSUE TITLE
Legacy Apps

### ISSUE THREAD

**Issue by GbGp** [OpenAMP/openamp-system-reference#61]
Hello, I noticed that the -DWITH_APP options in the open-amp repo has been deprecated and that I should get example applications from this repo. On the other way, all baremetal examples are under a "legacy" folder. 

Is the functionality shown there still supported? Any special care I should follow, for example, regarding the remoteproc examples?

**Comment by tnmysh** [comment]
@GbGp Functionality there is still supported. The apps are not new development and just move from open-amp library to new repo hence then name legacy_apps.
